# Generated by Django 5.1.1 on 2024-11-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('Human Resources', 'Human Resources'), ('Data Analyst', 'Data Analyst'), ('Digital Marketing', 'Digital Marketing'), ('UI Development', 'UI Development'), ('Full stack Python', 'Full stack Python'), ('UI/UX Designing', 'UI/UX Designing'), ('Full stack Java', 'Full stack Java'), ('AWS DevOps', 'AWS DevOps'), ('Gen AI', 'Gen AI')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(blank=True, choices=[('Strong', 'Strong'), ('Follow up', 'Follow up'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Wrong Number', 'Wrong Number'), ('Joined', 'Joined'), ('New', 'New')], default='New', max_length=40, null=True)),
                ('source', models.CharField(blank=True, choices=[('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('JustDial', 'JustDial'), ('Webenquiry', 'Webenquiry'), ('GoogleAds', 'GoogleAds'), ('BNI leads', 'BNI leads')], max_length=50, null=True)),
                ('lead_number', models.IntegerField(default=1, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course')),
            ],
        ),
    ]
