# Generated by Django 5.1.1 on 2024-11-13 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_lead_location_alter_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='date_of_joining',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
