# Generated by Django 5.1.1 on 2024-11-21 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_useractivity_timestamp_alter_useractivity_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('courses_opted', models.CharField(max_length=150)),
                ('mode_of_training', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=50)),
                ('tentative_date_of_joining_course', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
