# Generated by Django 5.1.1 on 2024-11-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='address',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='courses_opted',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='courses_opted',
            field=models.ManyToManyField(to='website.course'),
        ),
    ]
