# Generated by Django 5.1.1 on 2024-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_enrollment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='lead_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('ADD', 'Added'), ('EDIT', 'Edited'), ('DELETE', 'Deleted')], max_length=50),
        ),
    ]
