# Generated by Django 5.1.1 on 2024-11-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_enrollment_lead_number_alter_useractivity_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='lead_number',
            new_name='enrollment_number',
        ),
    ]
