# Generated by Django 5.1.1 on 2024-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_lead_number_enrollment_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
