# Generated by Django 5.1.1 on 2024-11-26 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_lead_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
