# Generated by Django 5.1.1 on 2024-12-05 06:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_lead_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+91\\d{10}$', 'Phone number must be in the format +91XXXXXXXXXX')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.course'),
        ),
    ]
