# Generated by Django 5.1.1 on 2024-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_enrollment_phone_alter_lead_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='course_opted',
            field=models.ManyToManyField(blank=True, to='website.course'),
        ),
    ]
