# Generated by Django 5.1.1 on 2024-12-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_trainer_course_opted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='course_opted',
            new_name='courses_opted',
        ),
    ]
