# Generated by Django 5.1.1 on 2024-12-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_enrollment_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
