# Generated by Django 5.1.1 on 2024-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
