# Generated by Django 5.1.1 on 2025-01-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_enrollment_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_name']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['enrollment_number']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['lead_number']},
        ),
    ]
